[package]
name = "bitx"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "a lightweight bit-level crate"
repository = "https://github.com/cradiy/bitx.git"
keywords = ["bit", "no_std"]

[features]
copy = []
bit128 = []
dev = []

[dependencies]
op = "0.1.3"
